/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tetris;

import Tetris.global.config.entity.MainConfig;
import Tetris.view.frame.game.GameFrame;

import java.awt.*;

public class App {

    public static void main(String[] args) {
        MainConfig mainConfig = MainConfig.getInstance();

        EventQueue.invokeLater(() -> {

            GameFrame gameFrame = new GameFrame(mainConfig.getWindowSize(), mainConfig.getDifficulty());
            gameFrame.setVisible(true);
        });
    }
}
