/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tetris;

import Tetris.global.config.entity.MainConfig;
import Tetris.view.frame.IndexFrame;
import Tetris.view.frame.game.GameFrame;

import java.awt.*;

public class App {

    public static void main(String[] args) {
        new IndexFrame();
    }
}
